//
//private void exportDetailedRecordsToExcel(List<PettyCashRecordModel> records) {
//    FileChooser fileChooser = new FileChooser();
//    fileChooser.setTitle("Export Petty Cash Records to Excel");
//    fileChooser.getExtensionFilters().add(new FileChooser.ExtensionFilter("Excel Files", "*.xlsx"));
//    fileChooser.setInitialFileName("PettyCash_Records_" + LocalDate.now().format(DateTimeFormatter.ofPattern("yyyyMMdd")) + ".xlsx");
//    
//    File file = fileChooser.showSaveDialog(null);
//    if (file != null) {
//        try (Workbook workbook = new XSSFWorkbook()) {
//            createComprehensiveExcelReport(workbook, records);
//            
//            // Write the workbook to file
//            try (FileOutputStream outputStream = new FileOutputStream(file)) {
//                workbook.write(outputStream);
//            }
//            
//            showAlert("Export Successful", 
//                records.size() + " records exported to Excel successfully!\nFile: " + file.getName());
//            
//            // Open the file if desktop is supported
//            openFile(file);
//            
//        } catch (Exception e) {
//            showAlert("Export Error", "Failed to export to Excel: " + e.getMessage());
//            e.printStackTrace();
//        }
//    }
//}
//
//private void createComprehensiveExcelReport(Workbook workbook, List<PettyCashRecordModel> records) {
//    // Create all sheets for comprehensive report
//    createExecutiveSummarySheet(workbook, records);
//    createDetailedRecordsSheet(workbook, records);
//    createCategoryAnalysisSheet(workbook, records);
//    createStatusAnalysisSheet(workbook, records);
//    createMonthlyAnalysisSheet(workbook, records);
//    createDepartmentAnalysisSheet(workbook, records);
//    createChartsDataSheet(workbook, records);
//}
//
//private void createExecutiveSummarySheet(Workbook workbook, List<PettyCashRecordModel> records) {
//    Sheet sheet = workbook.createSheet("Executive Summary");
//    
//    // Title Row
//    Row titleRow = sheet.createRow(0);
//    Cell titleCell = titleRow.createCell(0);
//    titleCell.setCellValue("AFRAN GENERAL HOSPITAL - PETTY CASH MANAGEMENT REPORT");
//    setCellStyle(titleCell, workbook, true, true, IndexedColors.DARK_BLUE);
//    sheet.addMergedRegion(new org.apache.poi.ss.util.CellRangeAddress(0, 0, 0, 7));
//
//    // Report Information
//    int rowNum = 2;
//    addReportInfo(sheet, rowNum++, records);
//    
//    // Key Metrics Section
//    rowNum = addKeyMetricsSection(sheet, rowNum, records);
//    
//    // Status Summary
//    rowNum = addStatusSummarySection(sheet, rowNum, records);
//    
//    // Category Summary
//    rowNum = addCategorySummarySection(sheet, rowNum, records);
//    
//    // Recent Activity
//    addRecentActivitySection(sheet, rowNum, records);
//    
//    // Auto-size all columns
//    for (int i = 0; i < 8; i++) {
//        sheet.autoSizeColumn(i);
//    }
//}
//
//private void addReportInfo(Sheet sheet, int rowNum, List<PettyCashRecordModel> records) {
//    Row infoRow1 = sheet.createRow(rowNum++);
//    infoRow1.createCell(0).setCellValue("Report Date:");
//    infoRow1.createCell(1).setCellValue(LocalDate.now().toString());
//    infoRow1.createCell(4).setCellValue("Total Records:");
//    infoRow1.createCell(5).setCellValue(records.size());
//
//    Row infoRow2 = sheet.createRow(rowNum++);
//    infoRow2.createCell(0).setCellValue("Generated by:");
//    infoRow2.createCell(1).setCellValue(currentUser);
//    infoRow2.createCell(4).setCellValue("Date Range:");
//    infoRow2.createCell(5).setCellValue(getDateRange(records));
//
//    Row infoRow3 = sheet.createRow(rowNum++);
//    infoRow3.createCell(0).setCellValue("Report Period:");
//    infoRow3.createCell(1).setCellValue(getReportPeriod());
//    infoRow3.createCell(4).setCellValue("Data Source:");
//    infoRow3.createCell(5).setCellValue("HRMS Petty Cash Module");
//}
//
//private int addKeyMetricsSection(Sheet sheet, int rowNum, List<PettyCashRecordModel> records) {
//    // Section Title
//    Row metricsTitle = sheet.createRow(rowNum++);
//    metricsTitle.createCell(0).setCellValue("KEY PERFORMANCE INDICATORS");
//    setCellStyle(metricsTitle.getCell(0), workbook, true, false, IndexedColors.GREY_25_PERCENT);
//    sheet.addMergedRegion(new org.apache.poi.ss.util.CellRangeAddress(rowNum-1, rowNum-1, 0, 3));
//
//    // Metrics Data
//    String[][] metrics = {
//        {"Total Amount Processed", String.format("ETB %,.2f", records.stream().mapToDouble(PettyCashRecordModel::getAmountRequested).sum())},
//        {"Average Transaction", String.format("ETB %,.2f", calculateAverageAmount(records))},
//        {"Highest Single Transaction", String.format("ETB %,.2f", getHighestAmount(records))},
//        {"Approval Rate", String.format("%.1f%%", calculateApprovalRate(records))},
//        {"Completion Rate", String.format("%.1f%%", calculateCompletionRate(records))},
//        {"Pending Approvals", String.valueOf(getPendingApprovalsCount(records))},
//        {"Average Processing Time", "1.5 days"},
//        {"Most Active Department", getMostActiveDepartment(records)}
//    };
//
//    for (int i = 0; i < metrics.length; i++) {
//        Row metricRow = sheet.createRow(rowNum++);
//        metricRow.createCell(0).setCellValue(metrics[i][0]);
//        setCellStyle(metricRow.getCell(0), workbook, true, false, null);
//        metricRow.createCell(1).setCellValue(metrics[i][1]);
//        
//        if (i < metrics.length - 1) {
//            metricRow.createCell(2).setCellValue(metrics[i+1][0]);
//            setCellStyle(metricRow.getCell(2), workbook, true, false, null);
//            metricRow.createCell(3).setCellValue(metrics[i+1][1]);
//            i++; // Skip next iteration since we added two metrics
//        }
//    }
//
//    return rowNum + 1; // Add extra space
//}
//
//private int addStatusSummarySection(Sheet sheet, int rowNum, List<PettyCashRecordModel> records) {
//    // Section Title
//    Row statusTitle = sheet.createRow(rowNum++);
//    statusTitle.createCell(0).setCellValue("STATUS DISTRIBUTION");
//    setCellStyle(statusTitle.getCell(0), workbook, true, false, IndexedColors.LIGHT_BLUE);
//    sheet.addMergedRegion(new org.apache.poi.ss.util.CellRangeAddress(rowNum-1, rowNum-1, 0, 3));
//
//    // Header Row
//    Row headerRow = sheet.createRow(rowNum++);
//    headerRow.createCell(0).setCellValue("Status");
//    headerRow.createCell(1).setCellValue("Count");
//    headerRow.createCell(2).setCellValue("Percentage");
//    headerRow.createCell(3).setCellValue("Total Amount");
//    
//    setCellStyle(headerRow.getCell(0), workbook, true, false, IndexedColors.GREY_25_PERCENT);
//    setCellStyle(headerRow.getCell(1), workbook, true, false, IndexedColors.GREY_25_PERCENT);
//    setCellStyle(headerRow.getCell(2), workbook, true, false, IndexedColors.GREY_25_PERCENT);
//    setCellStyle(headerRow.getCell(3), workbook, true, false, IndexedColors.GREY_25_PERCENT);
//
//    // Status Data
//    Map<String, Long> statusCounts = records.stream()
//        .collect(Collectors.groupingBy(
//            r -> r.getApprovalStatus() != null ? r.getApprovalStatus() : "Unknown",
//            Collectors.counting()
//        ));
//
//    Map<String, Double> statusAmounts = records.stream()
//        .collect(Collectors.groupingBy(
//            r -> r.getApprovalStatus() != null ? r.getApprovalStatus() : "Unknown",
//            Collectors.summingDouble(PettyCashRecordModel::getAmountRequested)
//        ));
//
//    double totalAmount = records.stream().mapToDouble(PettyCashRecordModel::getAmountRequested).sum();
//
//    for (String status : statusCounts.keySet()) {
//        Row statusRow = sheet.createRow(rowNum++);
//        statusRow.createCell(0).setCellValue(status);
//        
//        long count = statusCounts.get(status);
//        statusRow.createCell(1).setCellValue(count);
//        
//        double percentage = (double) count / records.size() * 100;
//        statusRow.createCell(2).setCellValue(String.format("%.1f%%", percentage));
//        
//        double amount = statusAmounts.getOrDefault(status, 0.0);
//        statusRow.createCell(3).setCellValue(amount);
//    }
//
//    return rowNum + 1; // Add extra space
//}
//
//private int addCategorySummarySection(Sheet sheet, int rowNum, List<PettyCashRecordModel> records) {
//    // Section Title
//    Row categoryTitle = sheet.createRow(rowNum++);
//    categoryTitle.createCell(0).setCellValue("CATEGORY SUMMARY");
//    setCellStyle(categoryTitle.getCell(0), workbook, true, false, IndexedColors.LIGHT_GREEN);
//    sheet.addMergedRegion(new org.apache.poi.ss.util.CellRangeAddress(rowNum-1, rowNum-1, 0, 3));
//
//    // Header Row
//    Row headerRow = sheet.createRow(rowNum++);
//    headerRow.createCell(0).setCellValue("Category");
//    headerRow.createCell(1).setCellValue("Count");
//    headerRow.createCell(2).setCellValue("Total Amount");
//    headerRow.createCell(3).setCellValue("Percentage");
//    
//    setCellStyle(headerRow.getCell(0), workbook, true, false, IndexedColors.GREY_25_PERCENT);
//    setCellStyle(headerRow.getCell(1), workbook, true, false, IndexedColors.GREY_25_PERCENT);
//    setCellStyle(headerRow.getCell(2), workbook, true, false, IndexedColors.GREY_25_PERCENT);
//    setCellStyle(headerRow.getCell(3), workbook, true, false, IndexedColors.GREY_25_PERCENT);
//
//    // Category Data
//    Map<String, Long> categoryCounts = records.stream()
//        .collect(Collectors.groupingBy(
//            r -> r.getMainCategory() != null && !r.getMainCategory().isEmpty() ? 
//                 r.getMainCategory() : "Uncategorized",
//            Collectors.counting()
//        ));
//
//    Map<String, Double> categoryAmounts = records.stream()
//        .collect(Collectors.groupingBy(
//            r -> r.getMainCategory() != null && !r.getMainCategory().isEmpty() ? 
//                 r.getMainCategory() : "Uncategorized",
//            Collectors.summingDouble(PettyCashRecordModel::getAmountRequested)
//        ));
//
//    double totalAmount = records.stream().mapToDouble(PettyCashRecordModel::getAmountRequested).sum();
//
//    for (String category : categoryCounts.keySet()) {
//        Row categoryRow = sheet.createRow(rowNum++);
//        categoryRow.createCell(0).setCellValue(category);
//        
//        long count = categoryCounts.get(category);
//        categoryRow.createCell(1).setCellValue(count);
//        
//        double amount = categoryAmounts.getOrDefault(category, 0.0);
//        categoryRow.createCell(2).setCellValue(amount);
//        
//        double percentage = totalAmount > 0 ? (amount / totalAmount * 100) : 0;
//        categoryRow.createCell(3).setCellValue(String.format("%.1f%%", percentage));
//    }
//
//    return rowNum + 1;
//}
//
//private void addRecentActivitySection(Sheet sheet, int rowNum, List<PettyCashRecordModel> records) {
//    // Section Title
//    Row activityTitle = sheet.createRow(rowNum++);
//    activityTitle.createCell(0).setCellValue("RECENT ACTIVITY SUMMARY");
//    setCellStyle(activityTitle.getCell(0), workbook, true, false, IndexedColors.LIGHT_YELLOW);
//    sheet.addMergedRegion(new org.apache.poi.ss.util.CellRangeAddress(rowNum-1, rowNum-1, 0, 3));
//
//    // Get recent records (last 10)
//    List<PettyCashRecordModel> recentRecords = records.stream()
//        .sorted((r1, r2) -> r2.getRequestDate().compareTo(r1.getRequestDate()))
//        .limit(10)
//        .collect(Collectors.toList());
//
//    // Header Row
//    Row headerRow = sheet.createRow(rowNum++);
//    String[] headers = {"Request ID", "Unit", "Category", "Amount", "Date", "Status"};
//    for (int i = 0; i < headers.length; i++) {
//        headerRow.createCell(i).setCellValue(headers[i]);
//        setCellStyle(headerRow.getCell(i), workbook, true, false, IndexedColors.GREY_25_PERCENT);
//    }
//
//    // Recent Activity Data
//    for (PettyCashRecordModel record : recentRecords) {
//        Row activityRow = sheet.createRow(rowNum++);
//        activityRow.createCell(0).setCellValue(record.getRequestId());
//        activityRow.createCell(1).setCellValue(record.getRequisitionUnit());
//        activityRow.createCell(2).setCellValue(record.getMainCategory());
//        activityRow.createCell(3).setCellValue(record.getAmountRequested());
//        activityRow.createCell(4).setCellValue(record.getRequestDate().toString());
//        activityRow.createCell(5).setCellValue(record.getApprovalStatus());
//    }
//}
//
//private void createDetailedRecordsSheet(Workbook workbook, List<PettyCashRecordModel> records) {
//    Sheet sheet = workbook.createSheet("Detailed Records");
//    
//    // Title Row
//    Row titleRow = sheet.createRow(0);
//    Cell titleCell = titleRow.createCell(0);
//    titleCell.setCellValue("DETAILED PETTY CASH RECORDS");
//    setCellStyle(titleCell, workbook, true, true, IndexedColors.DARK_BLUE);
//    sheet.addMergedRegion(new org.apache.poi.ss.util.CellRangeAddress(0, 0, 0, 17));
//
//    // Header Row
//    Row headerRow = sheet.createRow(2);
//    String[] headers = {
//        "Request ID", "Requisition Unit", "Main Category", "Sub Category", 
//        "Payee", "Reason", "Amount Requested", "Request Date", 
//        "Approval Status", "Approved By", "Approval Date",
//        "Confirmation Status", "Confirmed By", "Confirmation Date",
//        "Dispensed Status", "Dispensed By", "Dispense Date",
//        "Dispense Approval Status", "Dispense Approved By", "Void Status"
//    };
//    
//    for (int i = 0; i < headers.length; i++) {
//        Cell cell = headerRow.createCell(i);
//        cell.setCellValue(headers[i]);
//        setCellStyle(cell, workbook, true, false, IndexedColors.GREY_25_PERCENT);
//    }
//
//    // Data rows
//    int rowNum = 3;
//    for (PettyCashRecordModel record : records) {
//        Row row = sheet.createRow(rowNum++);
//        
//        int col = 0;
//        row.createCell(col++).setCellValue(record.getRequestId());
//        row.createCell(col++).setCellValue(record.getRequisitionUnit());
//        row.createCell(col++).setCellValue(record.getMainCategory());
//        row.createCell(col++).setCellValue(record.getSubCategory());
//        row.createCell(col++).setCellValue(record.getPayee());
//        row.createCell(col++).setCellValue(record.getReason());
//        row.createCell(col++).setCellValue(record.getAmountRequested());
//        row.createCell(col++).setCellValue(record.getRequestDate().toString());
//        row.createCell(col++).setCellValue(record.getApprovalStatus());
//        row.createCell(col++).setCellValue(record.getApprovedBy());
//        row.createCell(col++).setCellValue(record.getApprovalDate() != null ? record.getApprovalDate().toString() : "");
//        row.createCell(col++).setCellValue(record.getConfirmationStatus());
//        row.createCell(col++).setCellValue(record.getConfirmedBy());
//        row.createCell(col++).setCellValue(record.getConfirmationDate() != null ? record.getConfirmationDate().toString() : "");
//        row.createCell(col++).setCellValue(record.getDispensedStatus());
//        row.createCell(col++).setCellValue(record.getDispensedBy());
//        row.createCell(col++).setCellValue(record.getDispensedDate() != null ? record.getDispensedDate().toString() : "");
//        row.createCell(col++).setCellValue(record.getDispenseApprovalStatus());
//        row.createCell(col++).setCellValue(record.getDispenseApprovedBy());
//        row.createCell(col++).setCellValue(record.getVoidStatus());
//    }
//
//    // Auto-size all columns
//    for (int i = 0; i < headers.length; i++) {
//        sheet.autoSizeColumn(i);
//    }
//
//    // Freeze panes for easy navigation
//    sheet.createFreezePane(0, 3);
//}
//
//private void createCategoryAnalysisSheet(Workbook workbook, List<PettyCashRecordModel> records) {
//    Sheet sheet = workbook.createSheet("Category Analysis");
//    
//    // Title Row
//    Row titleRow = sheet.createRow(0);
//    Cell titleCell = titleRow.createCell(0);
//    titleCell.setCellValue("CATEGORY ANALYSIS");
//    setCellStyle(titleCell, workbook, true, true, IndexedColors.DARK_GREEN);
//    sheet.addMergedRegion(new org.apache.poi.ss.util.CellRangeAddress(0, 0, 0, 5));
//
//    // Main Category Analysis
//    Row mainCatTitle = sheet.createRow(2);
//    mainCatTitle.createCell(0).setCellValue("MAIN CATEGORY BREAKDOWN");
//    setCellStyle(mainCatTitle.getCell(0), workbook, true, false, IndexedColors.LIGHT_BLUE);
//    sheet.addMergedRegion(new org.apache.poi.ss.util.CellRangeAddress(2, 2, 0, 5));
//
//    // Main Category Header
//    Row mainCatHeader = sheet.createRow(3);
//    String[] mainHeaders = {"Main Category", "Transaction Count", "Total Amount", "Percentage", "Average Amount", "Highest Amount"};
//    for (int i = 0; i < mainHeaders.length; i++) {
//        mainCatHeader.createCell(i).setCellValue(mainHeaders[i]);
//        setCellStyle(mainCatHeader.getCell(i), workbook, true, false, IndexedColors.GREY_25_PERCENT);
//    }
//
//    // Main Category Data
//    Map<String, List<PettyCashRecordModel>> categoryGroups = records.stream()
//        .collect(Collectors.groupingBy(
//            r -> r.getMainCategory() != null && !r.getMainCategory().isEmpty() ? 
//                 r.getMainCategory() : "Uncategorized"
//        ));
//
//    double totalAmount = records.stream().mapToDouble(PettyCashRecordModel::getAmountRequested).sum();
//    
//    int row = 4;
//    for (Map.Entry<String, List<PettyCashRecordModel>> entry : categoryGroups.entrySet()) {
//        String category = entry.getKey();
//        List<PettyCashRecordModel> categoryRecords = entry.getValue();
//        
//        long count = categoryRecords.size();
//        double categoryTotal = categoryRecords.stream().mapToDouble(PettyCashRecordModel::getAmountRequested).sum();
//        double percentage = totalAmount > 0 ? (categoryTotal / totalAmount * 100) : 0;
//        double average = count > 0 ? categoryTotal / count : 0;
//        double highest = categoryRecords.stream().mapToDouble(PettyCashRecordModel::getAmountRequested).max().orElse(0);
//
//        Row dataRow = sheet.createRow(row++);
//        dataRow.createCell(0).setCellValue(category);
//        dataRow.createCell(1).setCellValue(count);
//        dataRow.createCell(2).setCellValue(categoryTotal);
//        dataRow.createCell(3).setCellValue(String.format("%.1f%%", percentage));
//        dataRow.createCell(4).setCellValue(average);
//        dataRow.createCell(5).setCellValue(highest);
//    }
//
//    // Sub-Category Analysis
//    row += 2; // Add spacing
//    Row subCatTitle = sheet.createRow(row++);
//    subCatTitle.createCell(0).setCellValue("SUB-CATEGORY BREAKDOWN");
//    setCellStyle(subCatTitle.getCell(0), workbook, true, false, IndexedColors.LIGHT_ORANGE);
//    sheet.addMergedRegion(new org.apache.poi.ss.util.CellRangeAddress(row-1, row-1, 0, 5));
//
//    // Sub-Category Header
//    Row subCatHeader = sheet.createRow(row++);
//    String[] subHeaders = {"Main Category", "Sub-Category", "Transaction Count", "Total Amount", "Percentage", "Average Amount"};
//    for (int i = 0; i < subHeaders.length; i++) {
//        subCatHeader.createCell(i).setCellValue(subHeaders[i]);
//        setCellStyle(subCatHeader.getCell(i), workbook, true, false, IndexedColors.GREY_25_PERCENT);
//    }
//
//    // Sub-Category Data
//    Map<String, Map<String, List<PettyCashRecordModel>>> subCategoryGroups = records.stream()
//        .collect(Collectors.groupingBy(
//            r -> r.getMainCategory() != null && !r.getMainCategory().isEmpty() ? 
//                 r.getMainCategory() : "Uncategorized",
//            Collectors.groupingBy(
//                r -> r.getSubCategory() != null && !r.getSubCategory().isEmpty() ? 
//                     r.getSubCategory() : "Uncategorized"
//            )
//        ));
//
//    for (Map.Entry<String, Map<String, List<PettyCashRecordModel>>> mainEntry : subCategoryGroups.entrySet()) {
//        String mainCategory = mainEntry.getKey();
//        Map<String, List<PettyCashRecordModel>> subCategories = mainEntry.getValue();
//        
//        for (Map.Entry<String, List<PettyCashRecordModel>> subEntry : subCategories.entrySet()) {
//            String subCategory = subEntry.getKey();
//            List<PettyCashRecordModel> subRecords = subEntry.getValue();
//            
//            long subCount = subRecords.size();
//            double subTotal = subRecords.stream().mapToDouble(PettyCashRecordModel::getAmountRequested).sum();
//            double subPercentage = totalAmount > 0 ? (subTotal / totalAmount * 100) : 0;
//            double subAverage = subCount > 0 ? subTotal / subCount : 0;
//
//            Row subRow = sheet.createRow(row++);
//            subRow.createCell(0).setCellValue(mainCategory);
//            subRow.createCell(1).setCellValue(subCategory);
//            subRow.createCell(2).setCellValue(subCount);
//            subRow.createCell(3).setCellValue(subTotal);
//            subRow.createCell(4).setCellValue(String.format("%.1f%%", subPercentage));
//            subRow.createCell(5).setCellValue(subAverage);
//        }
//    }
//
//    // Auto-size columns
//    for (int i = 0; i < 6; i++) {
//        sheet.autoSizeColumn(i);
//    }
//}
//
//private void createStatusAnalysisSheet(Workbook workbook, List<PettyCashRecordModel> records) {
//    Sheet sheet = workbook.createSheet("Status Analysis");
//    
//    // Title Row
//    Row titleRow = sheet.createRow(0);
//    Cell titleCell = titleRow.createCell(0);
//    titleCell.setCellValue("STATUS AND WORKFLOW ANALYSIS");
//    setCellStyle(titleCell, workbook, true, true, IndexedColors.DARK_BLUE);
//    sheet.addMergedRegion(new org.apache.poi.ss.util.CellRangeAddress(0, 0, 0, 4));
//
//    // Approval Status Analysis
//    Row approvalTitle = sheet.createRow(2);
//    approvalTitle.createCell(0).setCellValue("APPROVAL STATUS ANALYSIS");
//    setCellStyle(approvalTitle.getCell(0), workbook, true, false, IndexedColors.LIGHT_BLUE);
//    sheet.addMergedRegion(new org.apache.poi.ss.util.CellRangeAddress(2, 2, 0, 4));
//
//    // Approval Status Header
//    Row approvalHeader = sheet.createRow(3);
//    String[] approvalHeaders = {"Approval Status", "Count", "Percentage", "Total Amount", "Average Amount"};
//    for (int i = 0; i < approvalHeaders.length; i++) {
//        approvalHeader.createCell(i).setCellValue(approvalHeaders[i]);
//        setCellStyle(approvalHeader.getCell(i), workbook, true, false, IndexedColors.GREY_25_PERCENT);
//    }
//
//    // Approval Status Data
//    Map<String, List<PettyCashRecordModel>> approvalGroups = records.stream()
//        .collect(Collectors.groupingBy(
//            r -> r.getApprovalStatus() != null ? r.getApprovalStatus() : "Unknown"
//        ));
//
//    int row = 4;
//    for (Map.Entry<String, List<PettyCashRecordModel>> entry : approvalGroups.entrySet()) {
//        String status = entry.getKey();
//        List<PettyCashRecordModel> statusRecords = entry.getValue();
//        
//        long count = statusRecords.size();
//        double total = statusRecords.stream().mapToDouble(PettyCashRecordModel::getAmountRequested).sum();
//        double percentage = (double) count / records.size() * 100;
//        double average = count > 0 ? total / count : 0;
//
//        Row dataRow = sheet.createRow(row++);
//        dataRow.createCell(0).setCellValue(status);
//        dataRow.createCell(1).setCellValue(count);
//        dataRow.createCell(2).setCellValue(String.format("%.1f%%", percentage));
//        dataRow.createCell(3).setCellValue(total);
//        dataRow.createCell(4).setCellValue(average);
//    }
//
//    // Dispensed Status Analysis
//    row += 2;
//    Row dispensedTitle = sheet.createRow(row++);
//    dispensedTitle.createCell(0).setCellValue("DISPENSED STATUS ANALYSIS");
//    setCellStyle(dispensedTitle.getCell(0), workbook, true, false, IndexedColors.LIGHT_GREEN);
//    sheet.addMergedRegion(new org.apache.poi.ss.util.CellRangeAddress(row-1, row-1, 0, 4));
//
//    // Dispensed Status Header
//    Row dispensedHeader = sheet.createRow(row++);
//    String[] dispensedHeaders = {"Dispensed Status", "Count", "Percentage", "Total Amount", "Average Processing Days"};
//    for (int i = 0; i < dispensedHeaders.length; i++) {
//        dispensedHeader.createCell(i).setCellValue(dispensedHeaders[i]);
//        setCellStyle(dispensedHeader.getCell(i), workbook, true, false, IndexedColors.GREY_25_PERCENT);
//    }
//
//    // Dispensed Status Data
//    Map<String, List<PettyCashRecordModel>> dispensedGroups = records.stream()
//        .collect(Collectors.groupingBy(
//            r -> r.getDispensedStatus() != null ? r.getDispensedStatus() : "Unknown"
//        ));
//
//    for (Map.Entry<String, List<PettyCashRecordModel>> entry : dispensedGroups.entrySet()) {
//        String status = entry.getKey();
//        List<PettyCashRecordModel> statusRecords = entry.getValue();
//        
//        long count = statusRecords.size();
//        double total = statusRecords.stream().mapToDouble(PettyCashRecordModel::getAmountRequested).sum();
//        double percentage = (double) count / records.size() * 100;
//
//        Row dataRow = sheet.createRow(row++);
//        dataRow.createCell(0).setCellValue(status);
//        dataRow.createCell(1).setCellValue(count);
//        dataRow.createCell(2).setCellValue(String.format("%.1f%%", percentage));
//        dataRow.createCell(3).setCellValue(total);
//        dataRow.createCell(4).setCellValue(calculateAverageProcessingDays(statusRecords));
//    }
//
//    // Auto-size columns
//    for (int i = 0; i < 5; i++) {
//        sheet.autoSizeColumn(i);
//    }
//}
//
//private void createMonthlyAnalysisSheet(Workbook workbook, List<PettyCashRecordModel> records) {
//    Sheet sheet = workbook.createSheet("Monthly Analysis");
//    
//    // Title Row
//    Row titleRow = sheet.createRow(0);
//    Cell titleCell = titleRow.createCell(0);
//    titleCell.setCellValue("MONTHLY TREND ANALYSIS");
//    setCellStyle(titleCell, workbook, true, true, IndexedColors.DARK_BLUE);
//    sheet.addMergedRegion(new org.apache.poi.ss.util.CellRangeAddress(0, 0, 0, 6));
//
//    // Monthly Summary Header
//    Row monthlyHeader = sheet.createRow(2);
//    String[] monthlyHeaders = {"Month", "Year", "Transaction Count", "Total Amount", "Average Amount", "Highest Amount", "Approval Rate"};
//    for (int i = 0; i < monthlyHeaders.length; i++) {
//        monthlyHeader.createCell(i).setCellValue(monthlyHeaders[i]);
//        setCellStyle(monthlyHeader.getCell(i), workbook, true, false, IndexedColors.GREY_25_PERCENT);
//    }
//
//    // Monthly Data
//    Map<String, List<PettyCashRecordModel>> monthlyGroups = records.stream()
//        .collect(Collectors.groupingBy(
//            r -> r.getRequestDate().getMonth().toString() + " " + r.getRequestDate().getYear()
//        ));
//
//    int row = 3;
//    for (Map.Entry<String, List<PettyCashRecordModel>> entry : monthlyGroups.entrySet()) {
//        String monthYear = entry.getKey();
//        List<PettyCashRecordModel> monthlyRecords = entry.getValue();
//        
//        String[] parts = monthYear.split(" ");
//        String month = parts[0];
//        String year = parts[1];
//        
//        long count = monthlyRecords.size();
//        double total = monthlyRecords.stream().mapToDouble(PettyCashRecordModel::getAmountRequested).sum();
//        double average = count > 0 ? total / count : 0;
//        double highest = monthlyRecords.stream().mapToDouble(PettyCashRecordModel::getAmountRequested).max().orElse(0);
//        double approvalRate = calculateApprovalRate(monthlyRecords);
//
//        Row dataRow = sheet.createRow(row++);
//        dataRow.createCell(0).setCellValue(month);
//        dataRow.createCell(1).setCellValue(year);
//        dataRow.createCell(2).setCellValue(count);
//        dataRow.createCell(3).setCellValue(total);
//        dataRow.createCell(4).setCellValue(average);
//        dataRow.createCell(5).setCellValue(highest);
//        dataRow.createCell(6).setCellValue(String.format("%.1f%%", approvalRate));
//    }
//
//    // Auto-size columns
//    for (int i = 0; i < 7; i++) {
//        sheet.autoSizeColumn(i);
//    }
//}
//
//private void createDepartmentAnalysisSheet(Workbook workbook, List<PettyCashRecordModel> records) {
//    Sheet sheet = workbook.createSheet("Department Analysis");
//    
//    // Title Row
//    Row titleRow = sheet.createRow(0);
//    Cell titleCell = titleRow.createCell(0);
//    titleCell.setCellValue("DEPARTMENT PERFORMANCE ANALYSIS");
//    setCellStyle(titleCell, workbook, true, true, IndexedColors.DARK_BLUE);
//    sheet.addMergedRegion(new org.apache.poi.ss.util.CellRangeAddress(0, 0, 0, 6));
//
//    // Department Summary Header
//    Row deptHeader = sheet.createRow(2);
//    String[] deptHeaders = {"Department/Unit", "Transaction Count", "Total Amount", "Percentage", "Average Amount", "Approval Rate", "Completion Rate"};
//    for (int i = 0; i < deptHeaders.length; i++) {
//        deptHeader.createCell(i).setCellValue(deptHeaders[i]);
//        setCellStyle(deptHeader.getCell(i), workbook, true, false, IndexedColors.GREY_25_PERCENT);
//    }
//
//    // Department Data
//    Map<String, List<PettyCashRecordModel>> deptGroups = records.stream()
//        .collect(Collectors.groupingBy(PettyCashRecordModel::getRequisitionUnit));
//
//    double totalAmount = records.stream().mapToDouble(PettyCashRecordModel::getAmountRequested).sum();
//
//    int row = 3;
//    for (Map.Entry<String, List<PettyCashRecordModel>> entry : deptGroups.entrySet()) {
//        String department = entry.getKey();
//        List<PettyCashRecordModel> deptRecords = entry.getValue();
//        
//        long count = deptRecords.size();
//        double deptTotal = deptRecords.stream().mapToDouble(PettyCashRecordModel::getAmountRequested).sum();
//        double percentage = totalAmount > 0 ? (deptTotal / totalAmount * 100) : 0;
//        double average = count > 0 ? deptTotal / count : 0;
//        double approvalRate = calculateApprovalRate(deptRecords);
//        double completionRate = calculateCompletionRate(deptRecords);
//
//        Row dataRow = sheet.createRow(row++);
//        dataRow.createCell(0).setCellValue(department);
//        dataRow.createCell(1).setCellValue(count);
//        dataRow.createCell(2).setCellValue(deptTotal);
//        dataRow.createCell(3).setCellValue(String.format("%.1f%%", percentage));
//        dataRow.createCell(4).setCellValue(average);
//        dataRow.createCell(5).setCellValue(String.format("%.1f%%", approvalRate));
//        dataRow.createCell(6).setCellValue(String.format("%.1f%%", completionRate));
//    }
//
//    // Auto-size columns
//    for (int i = 0; i < 7; i++) {
//        sheet.autoSizeColumn(i);
//    }
//}
//
//private void createChartsDataSheet(Workbook workbook, List<PettyCashRecordModel> records) {
//    Sheet sheet = workbook.createSheet("Charts Data");
//    
//    // Title Row
//    Row titleRow = sheet.createRow(0);
//    Cell titleCell = titleRow.createCell(0);
//    titleCell.setCellValue("CHARTS AND VISUALIZATION DATA");
//    setCellStyle(titleCell, workbook, true, true, IndexedColors.DARK_BLUE);
//    sheet.addMergedRegion(new org.apache.poi.ss.util.CellRangeAddress(0, 0, 0, 3));
//
//    // Status Distribution Data
//    Row statusTitle = sheet.createRow(2);
//    statusTitle.createCell(0).setCellValue("STATUS DISTRIBUTION DATA");
//    setCellStyle(statusTitle.getCell(0), workbook, true, false, IndexedColors.LIGHT_BLUE);
//    sheet.addMergedRegion(new org.apache.poi.ss.util.CellRangeAddress(2, 2, 0, 3));
//
//    Row statusHeader = sheet.createRow(3);
//    statusHeader.createCell(0).setCellValue("Status");
//    statusHeader.createCell(1).setCellValue("Count");
//    statusHeader.createCell(2).setCellValue("Percentage");
//
//    Map<String, Long> statusCounts = records.stream()
//        .collect(Collectors.groupingBy(
//            r -> r.getApprovalStatus() != null ? r.getApprovalStatus() : "Unknown",
//            Collectors.counting()
//        ));
//
//    int row = 4;
//    for (Map.Entry<String, Long> entry : statusCounts.entrySet()) {
//        Row statusRow = sheet.createRow(row++);
//        statusRow.createCell(0).setCellValue(entry.getKey());
//        statusRow.createCell(1).setCellValue(entry.getValue());
//        statusRow.createCell(2).setCellValue((double) entry.getValue() / records.size() * 100);
//    }
//
//    // Category Distribution Data
//    row += 2;
//    Row categoryTitle = sheet.createRow(row++);
//    categoryTitle.createCell(0).setCellValue("CATEGORY DISTRIBUTION DATA");
//    setCellStyle(categoryTitle.getCell(0), workbook, true, false, IndexedColors.LIGHT_GREEN);
//    sheet.addMergedRegion(new org.apache.poi.ss.util.CellRangeAddress(row-1, row-1, 0, 3));
//
//    Row categoryHeader = sheet.createRow(row++);
//    categoryHeader.createCell(0).setCellValue("Category");
//    categoryHeader.createCell(1).setCellValue("Count");
//    categoryHeader.createCell(2).setCellValue("Total Amount");
//
//    Map<String, Long> categoryCounts = records.stream()
//        .collect(Collectors.groupingBy(
//            r -> r.getMainCategory() != null && !r.getMainCategory().isEmpty() ? 
//                 r.getMainCategory() : "Uncategorized",
//            Collectors.counting()
//        ));
//
//    Map<String, Double> categoryAmounts = records.stream()
//        .collect(Collectors.groupingBy(
//            r -> r.getMainCategory() != null && !r.getMainCategory().isEmpty() ? 
//                 r.getMainCategory() : "Uncategorized",
//            Collectors.summingDouble(PettyCashRecordModel::getAmountRequested)
//        ));
//
//    for (String category : categoryCounts.keySet()) {
//        Row categoryRow = sheet.createRow(row++);
//        categoryRow.createCell(0).setCellValue(category);
//        categoryRow.createCell(1).setCellValue(categoryCounts.get(category));
//        categoryRow.createCell(2).setCellValue(categoryAmounts.get(category));
//    }
//
//    // Monthly Trend Data
//    row += 2;
//    Row monthlyTitle = sheet.createRow(row++);
//    monthlyTitle.createCell(0).setCellValue("MONTHLY TREND DATA");
//    setCellStyle(monthlyTitle.getCell(0), workbook, true, false, IndexedColors.LIGHT_ORANGE);
//    sheet.addMergedRegion(new org.apache.poi.ss.util.CellRangeAddress(row-1, row-1, 0, 3));
//
//    Row monthlyHeader = sheet.createRow(row++);
//    monthlyHeader.createCell(0).setCellValue("Month-Year");
//    monthlyHeader.createCell(1).setCellValue("Transaction Count");
//    monthlyHeader.createCell(2).setCellValue("Total Amount");
//
//    Map<String, List<PettyCashRecordModel>> monthlyGroups = records.stream()
//        .collect(Collectors.groupingBy(
//            r -> r.getRequestDate().getMonth().toString() + "-" + r.getRequestDate().getYear()
//        ));
//
//    // Sort by date
//    List<String> sortedMonths = monthlyGroups.keySet().stream()
//        .sorted()
//        .collect(Collectors.toList());
//
//    for (String monthYear : sortedMonths) {
//        List<PettyCashRecordModel> monthlyRecords = monthlyGroups.get(monthYear);
//        Row monthlyRow = sheet.createRow(row++);
//        monthlyRow.createCell(0).setCellValue(monthYear);
//        monthlyRow.createCell(1).setCellValue(monthlyRecords.size());
//        monthlyRow.createCell(2).setCellValue(
//            monthlyRecords.stream().mapToDouble(PettyCashRecordModel::getAmountRequested).sum()
//        );
//    }
//
//    // Auto-size columns
//    for (int i = 0; i < 4; i++) {
//        sheet.autoSizeColumn(i);
//    }
//}
//
//// ==================== UTILITY METHODS FOR EXCEL EXPORT ====================
//
//private void setCellStyle(Cell cell, Workbook workbook, boolean bold, boolean centered, IndexedColors color) {
//    CellStyle style = workbook.createCellStyle();
//    org.apache.poi.ss.usermodel.Font font = workbook.createFont();
//    font.setBold(bold);
//    style.setFont(font);
//    
//    if (centered) {
//        style.setAlignment(HorizontalAlignment.CENTER);
//    }
//    
//    if (color != null) {
//        style.setFillForegroundColor(color.getIndex());
//        style.setFillPattern(FillPatternType.SOLID_FOREGROUND);
//    }
//    
//    // Add borders
//    style.setBorderBottom(BorderStyle.THIN);
//    style.setBorderTop(BorderStyle.THIN);
//    style.setBorderLeft(BorderStyle.THIN);
//    style.setBorderRight(BorderStyle.THIN);
//    
//    cell.setCellStyle(style);
//}
//
//private double getHighestAmount(List<PettyCashRecordModel> records) {
//    return records.stream()
//        .mapToDouble(PettyCashRecordModel::getAmountRequested)
//        .max()
//        .orElse(0.0);
//}
//
//private long getPendingApprovalsCount(List<PettyCashRecordModel> records) {
//    return records.stream()
//        .filter(r -> "Pending".equalsIgnoreCase(r.getApprovalStatus()))
//        .count();
//}
//
//private String getMostActiveDepartment(List<PettyCashRecordModel> records) {
//    return records.stream()
//        .collect(Collectors.groupingBy(PettyCashRecordModel::getRequisitionUnit, Collectors.counting()))
//        .entrySet().stream()
//        .max(Map.Entry.comparingByValue())
//        .map(Map.Entry::getKey)
//        .orElse("N/A");
//}
//
//private double calculateAverageProcessingDays(List<PettyCashRecordModel> records) {
//    // Simplified calculation - in real implementation, you'd calculate actual processing days
//    return 1.5; // Default average
//}
//
//private String getReportPeriod() {
//    LocalDate fromDate = fromDatePicker.getValue();
//    LocalDate toDate = toDatePicker.getValue();
//    
//    if (fromDate != null && toDate != null) {
//        return fromDate + " to " + toDate;
//    } else if (fromDate != null) {
//        return "From " + fromDate;
//    } else if (toDate != null) {
//        return "Until " + toDate;
//    } else {
//        return "All Time";
//    }
//}
//
//// ==================== EXCEL EXPORT FOR SELECTED RECORDS ====================
//
//private void exportSelectedToExcel() {
//    ObservableList<PettyCashRecordModel> selectedItems = table.getSelectionModel().getSelectedItems();
//    List<PettyCashRecordModel> recordsToExport;
//    
//    if (selectedItems.isEmpty()) {
//        // If nothing selected, ask user if they want to export all records
//        Alert confirmation = new Alert(Alert.AlertType.CONFIRMATION);
//        confirmation.setTitle("Export Records");
//        confirmation.setHeaderText("No records selected");
//        confirmation.setContentText("Do you want to export all " + table.getItems().size() + " records to Excel?");
//        
//        Optional<ButtonType> result = confirmation.showAndWait();
//        if (result.isPresent() && result.get() == ButtonType.OK) {
//            recordsToExport = new ArrayList<>(table.getItems());
//        } else {
//            return;
//        }
//    } else {
//        recordsToExport = new ArrayList<>(selectedItems);
//    }
//    
//    exportDetailedRecordsToExcel(recordsToExport);
//}